// src/app/components/marker-detail/marker-detail.component.ts
import { Component, inject, OnInit, ViewChild } from '@angular/core';
import { ModalController, IonHeader, IonButton, IonToolbar, IonButtons, IonIcon, IonTitle, IonContent, IonInput } from '@ionic/angular/standalone';
import { Marker, Track } from '@model/model';
import { TranslatePipe } from '@ngx-translate/core';
import { mrkr } from '@services/mrkr';
import { TracksService } from '@services/tracks.service';
import { waitFor } from '@services/util';

@Component({
  selector: 'mppm-marker-detail',
  templateUrl: './marker-detail.component.html',
  styleUrls: ['./marker-detail.component.scss'],
  imports: [TranslatePipe, IonInput, IonContent, IonTitle, IonIcon, IonButtons, IonToolbar, IonHeader, IonButton],
})
export class MarkerDetailComponent implements OnInit {

  tracksService = inject(TracksService);
  modalController = inject(ModalController);

  mrkr = mrkr;

  track: Track;
  marker: Marker;

  title = '';

  @ViewChild('titleInput')
  titleInput: IonInput;

  save() {
    this.marker.title = this.title;
    this.tracksService.saveTracks();
    this.dismiss();
  }

  dismiss() {
    this.modalController.dismiss();
  }

  deleteMarker() {
    this.track.markers = this.track.markers.filter(it => it !== this.marker);
    this.tracksService.saveTracks();
    this.dismiss();
  }

  ngOnInit() {
    this.title = this.marker.title;
    waitFor(() => this.titleInput).then(inp => inp?.setFocus());
  }
}

<ion-header>
  <ion-toolbar>
    <ion-buttons slot="start">
      <ion-button (click)="dismiss()">
        <ion-icon name="arrow-back-outline"></ion-icon>
      </ion-button>
    </ion-buttons>
    <ion-title>{{ 'C_MARKER' | translate }} {{mrkr(marker?.value)}}</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>
  <div class="marker-detail-content">
    <ion-input [value]="title" (ionChange)="title = $event.detail.value" #titleInput
               clear-input [placeholder]="'C_DESCRIPTION' | translate"></ion-input>
    <ion-button class="save" (click)="save()">{{ 'C_SAVE' | translate }}</ion-button>

    <ion-button fill="outline" class="secondary-button" (click)="deleteMarker()">
      {{ 'C_DELETE' | translate }}
    </ion-button>
  </div>

</ion-content>

// src/components/MarkerDetail.svelte
<script lang="ts">
  import { modalController } from '$ionic/svelte';
  import IoIosArrowBack from 'svelte-icons/io/IoIosArrowBack.svelte';
  import { tracksService } from '$services/tracks.service';
  import { mrkr } from '$services/mrkr';
  import { _ } from 'svelte-i18n';
  import type { Marker, Track } from '$model/model';
  import { onMount } from 'svelte';
  import { waitFor } from '$services/util';
  import type { IonInput } from '@ionic/core/components/ion-input';

  export let track: Track;
  export let marker: Marker;

  let title = '';
  let titleInput: IonInput;

  function save() {
    marker.title = title;
    tracksService.saveTracks();
    dismiss();
  }

  function dismiss() {
    modalController.dismiss();
  }

  function deleteMarker() {
    track.markers = track.markers.filter(it => it !== marker);
    tracksService.saveTracks();
    dismiss();
  }

  onMount(() => {
    title = marker.title;
    waitFor(() => titleInput).then(inp => inp?.setFocus());
  });
</script>

<ion-header>
  <ion-toolbar>
    <ion-buttons>
      <ion-button on:click={dismiss}>
        <IoIosArrowBack/>
      </ion-button>
    </ion-buttons>
    <ion-title>{$_('C_MARKER')} {mrkr(marker?.value)}</ion-title>
  </ion-toolbar>
</ion-header>

<ion-content>
  <div class="marker-detail-content">
    <ion-input value={title} on:ionChange={e => title = e.detail.value} bind:this={titleInput}
               clear-input placeholder={$_('C_DESCRIPTION')}></ion-input>
    <ion-button class="save" on:click={save}>{$_('C_SAVE')}</ion-button>

    <ion-button fill="outline" class="secondary-button" on:click={deleteMarker}>
      {$_('C_DELETE')}
    </ion-button>
  </div>

</ion-content>

<style lang="scss">

  ion-content {
    height: 400px;
  }

  .marker-detail-content {
    padding: 16px;
    display: grid;
  }

  .save {
    margin-top: 20px;
  }

  .secondary-button {
    margin-top: 40px;
  }
</style>
